BooksLibrary/Controllers/BooksController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using BooksLibrary.Models;

namespace BooksLibrary.Controllers
{
    [Authorize]
    [Filters.ExceptionFilter]
    public class BooksController : Controller
    {
        private LibraryDatabaseEntities db = new LibraryDatabaseEntities();

        // GET: Books
        public ActionResult Index()
        {
            return View(db.Books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                throw new Exception("400");
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                throw new Exception("404");
            }
            return View(book);
        }

        // GET: Books/Create
        [Authorize(Roles = "Manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult Create([Bind(Include = "ISBN,author,name,publication_type,tome,compiler,language,translator,place_publication,publishing,year,number,price")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Books/Edit/5
        [Authorize(Roles = "Manager")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                throw new Exception("400");
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                throw new Exception("404");
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult Edit([Bind(Include = "ISBN,author,name,publication_type,tome,compiler,language,translator,place_publication,publishing,year,number,price")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager")]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                Book book = db.Books.Find(id);
                db.Books.Remove(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                throw new Exception("403");
            }
            
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BooksLibrary/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BooksLibrary.Models;

namespace BooksLibrary.Controllers
{
    [Authorize]
    [Authorize(Roles = "Admin")]
    [Filters.ExceptionFilter]
    public class UsersController : Controller
    {
        private DefaultConnectionEntities db = new DefaultConnectionEntities();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.AspNetUsers.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }

            ViewBag.roles = db.AspNetRoles.ToList();

            return View(aspNetUser);
        }

        // POST: Users/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                var role = Request.Form["Role"].ToString();
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.Database.ExecuteSqlCommand($@"
                    UPDATE [AspNetUserRoles]
                    SET [AspNetUserRoles].[RoleId] = (
                        SELECT [Id]
                        FROM [AspNetRoles]
                        WHERE [AspNetRoles].[Name] = '{role}'
                    )
                    WHERE [AspNetUserRoles].[UserId] = '{aspNetUser.Id}'
                ");
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BooksLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
 
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/font-awesome-4.7.0/css/font-awesome.css">
</head>
<body>
    <script src="@Url.Content("~/Scripts/delete.js")"></script>
    <link href="@Url.Content("~/Content/deleteDialog.css")" rel="stylesheet" type="text/css" />
    <div id="delete">
        <div>
            <p>Удалить?</p>
            <form id="delform" action="" method="post">
                @Html.AntiForgeryToken()
                <input type="submit" value="Да" onclick="del()" class="btn btn-danger delbut">
                <input type="button" value="Нет" onclick="hideDel()" class="btn btn-success delbut">
            </form>
        </div>
    </div>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Библиотека", "Index", "Books", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (User.IsInRole("Manager"))
                        {
                            <li>@Html.ActionLink("Книги", "Index", "Books")</li>
                            <li>@Html.ActionLink("Экземпляры", "Index", "Instances")</li>
                            <li>@Html.ActionLink("Читатели", "Index", "Readers")</li>
                            <li>@Html.ActionLink("Область знаний", "Index", "Knowledges")</li>
                            <li>@Html.ActionLink("Выдача книг", "Index", "Extraditions")</li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Пользователи", "Index", "Users")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            @*<hr />
            <footer></footer>*@
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <script src="/Scripts/BooksFilter.js"></script>        
</body>
</html>